# Generated by Django 5.1.4 on 2025-01-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
        migrations.AddField(
            model_name='posts',
            name='img2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='img3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='isdisabled',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='posts',
            name='islock',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='posts',
            name='isprivate',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='video_url',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='posts',
            name='posttype',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
