# Generated by Django 5.1.5 on 2025-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_posts_category_id_posts_img2_posts_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
