# Generated by Django 5.1.5 on 2025-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_posts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='islock',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
