# Generated by Django 5.1.5 on 2025-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_posts_islock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
