# Generated by Django 5.1.5 on 2025-03-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_posts_post_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='islock',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='isprivate',
        ),
    ]
