# Generated by Django 5.1.4 on 2025-01-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('state_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
    ]
