# Generated by Django 5.1.5 on 2025-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
