# Generated by Django 5.1.5 on 2025-02-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_notification_noti_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
