# Generated by Django 5.1.4 on 2025-01-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTime',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timing', models.TimeField()),
                ('end_timing', models.TimeField()),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_socialtime',
            },
        ),
    ]
