# Generated by Django 5.1.5 on 2025-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialtime',
            name='end_timing',
        ),
        migrations.RemoveField(
            model_name='socialtime',
            name='start_timing',
        ),
        migrations.AddField(
            model_name='socialtime',
            name='end_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='socialtime',
            name='social_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='socialtime',
            name='start_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
