# Generated by Django 5.1.5 on 2025-04-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTime', '0002_remove_socialtime_end_timing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtime',
            name='type',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='socialtime',
            name='user_id',
            field=models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
