# Generated by Django 5.1.5 on 2025-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTime', '0003_socialtime_type_alter_socialtime_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtime',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
