# Generated by Django 5.1.4 on 2025-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_comments',
            },
        ),
    ]
