# Generated by Django 5.1.4 on 2025-01-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_comments_comment_datetime_comments_user_id'),
        ('Posts', '0002_posts_category_id_posts_img2_posts_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Posts.posts'),
        ),
    ]
