# Generated by Django 5.1.5 on 2025-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_comments_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
