# Generated by Django 5.1.5 on 2025-02-28 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_alter_comments_comment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
