# Generated by Django 5.1.4 on 2025-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('colleges_id', models.AutoField(primary_key=True, serialize=False)),
                ('colleges_name', models.CharField(max_length=100)),
                ('colleges_logo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_colleges',
            },
        ),
    ]
