# Generated by Django 5.1.5 on 2025-03-31 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhotos',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_myphotos',
            },
        ),
    ]
