# Generated by Django 5.1.4 on 2025-01-22 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0002_posts_category_id_posts_img2_posts_img3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('like_datetime', models.DateTimeField(default=None)),
                ('post_id', models.ForeignKey(db_column='post_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Posts.posts')),
                ('user_id', models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_like/dislike',
            },
        ),
    ]
