# Generated by Django 5.1.4 on 2025-01-22 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0001_initial'),
        ('Posts', '0002_posts_category_id_posts_img2_posts_img3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='Posts.posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
