# Generated by Django 5.1.5 on 2025-03-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0002_alter_likes_post_id_alter_likes_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like_datetime',
        ),
    ]
