# Generated by Django 5.1.4 on 2025-01-22 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colleges', '0001_initial'),
        ('Degrees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('colleges_id', models.ForeignKey(db_column='colleges_id', on_delete=django.db.models.deletion.CASCADE, to='Colleges.colleges')),
                ('degree_id', models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.CASCADE, to='Degrees.degrees')),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_education',
            },
        ),
    ]
