# Generated by Django 5.1.5 on 2025-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_remove_education_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
