# Generated by Django 5.1.4 on 2025-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_degree',
            },
        ),
    ]
