# Generated by Django 5.1.5 on 2025-04-08 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('grpchat_id', models.AutoField(primary_key=True, serialize=False)),
                ('groups_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups_id', models.ForeignKey(db_column='groups_id', on_delete=django.db.models.deletion.CASCADE, to='Groups.usergroups')),
                ('sender_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
