# Generated by Django 5.1.5 on 2025-04-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupchat',
            table='tbl_groupchat',
        ),
    ]
