# Generated by Django 5.1.5 on 2025-02-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0002_extrainfo_aboutme_extrainfo_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='email',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
