# Generated by Django 5.1.5 on 2025-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0003_extrainfo_email_extrainfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='birthdate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='timechange_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='timing',
            field=models.TimeField(null=True),
        ),
    ]
