# Generated by Django 5.1.5 on 2025-02-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0004_alter_extrainfo_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='aboutme',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
