# Generated by Django 5.1.5 on 2025-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0005_alter_extrainfo_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='coverphoto',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
