# Generated by Django 5.1.5 on 2025-02-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0006_alter_extrainfo_coverphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='last_name',
        ),
    ]
