# Generated by Django 5.1.5 on 2025-02-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0007_remove_extrainfo_email_remove_extrainfo_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='profile',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
