# Generated by Django 5.1.5 on 2025-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0008_extrainfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='timing',
            field=models.TextField(null=True),
        ),
    ]
