# Generated by Django 5.1.5 on 2025-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0009_alter_extrainfo_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='is_online',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
