# Generated by Django 5.1.5 on 2025-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtraInfo', '0010_extrainfo_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='is_online',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
