# Generated by Django 5.1.5 on 2025-01-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('groups_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=35)),
                ('group_logo', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_groups',
            },
        ),
    ]
